version: v0.3.0

listeners:
  - type: model
    name: model_1
    address: 0.0.0.0
    port: 12000

model_providers:
  - model: openai/gpt-4o-mini
    access_key: $OPENAI_API_KEY

  - model: openai/gpt-4o
    access_key: $OPENAI_API_KEY
    default: true

  - model: openai/gpt-5.2
    access_key: $OPENAI_API_KEY

  - model: openai/gpt-4.1-mini
    access_key: $OPENAI_API_KEY

model_aliases:
  gpt-4-mini:
    target: openai/gpt-4o-mini

  gpt-4o:
    target: openai/gpt-4o

  gpt-5.2:
    target: openai/gpt-5.2

  gpt-4.1-mini:
    target: openai/gpt-4.1-mini

tracing:
  random_sampling: 100
