version: v0.3.0

filters:
  - id: content_guard
    url: http://content-guard:10500
    type: http

model_providers:
  - model: openai/gpt-4o-mini
    access_key: $OPENAI_API_KEY
    default: true

listeners:
  - type: model
    name: llm_gateway
    port: 12000
    filter_chain:
      - content_guard

tracing:
  random_sampling: 100
